theme: jekyll-theme-cayman
title: MaPLe
description: A novel Prompt Learning framework to adapt <i>both</i> vision and language branches of CLIP to improve alignment between the vision and language representations. <br> MaPLe demonstrates state-of-the-art results towards novel categories, cross-dataset transfer and datasets with domain shifts.
